import "./globals.css";
import type { Metadata } from "next";

//Fonts
import { inter } from "@/Fonts";

export const metadata: Metadata = {
  title: "Cabbage | The harmony of code and design!",
  description: "Generated by create next app"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} font-sans text-main`}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
