import "./globals.css";
import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";

//Fonts
import { inter } from "@/Fonts";

export const metadata: Metadata = {
  title: "Cabbage | The harmony of code and design!",
  description: "We're Pioneering Design-Driven Web Innovators. Where Vision Becomes Reality, Empowering startups, businesses, and ideas to flourish, solving challenges with the art of coding.",
  applicationName: "Cabbage web",
  keywords: ["edureka web development",
    "eclipse for web development",
    "flask web development",
    "node js web development",
    "python web development django",
    "qa web development",
    "qspiders web development course fees",
    "qt web development",
    "about page web design",
    "about web design",
    "adaptive web design",
    "adobe web design software",
    "app for web design",
    "@aw-web-design/x-default-browser",
    "web design online jobs",
    "web design online free",
    "web design online degree",
    "web design online course free",
    "web design picture",
    "web design photo",
    "web design page",
    "web design psd template free download",
    "web design qualification",
    "web design questionnaire",
    "web design questions and answers pdf",
    "web design salary in Bangladesh",
    "web design salary",
    "web design rules",
    "web design roadmap 2023",
    "web design roadmap",
    "web design ui",
    "web design USA",
    "web design upwork",
    "web design udemy",
    "web design ui ux",
    "web design UK",
    "web design university",
    "web design websites",
    "web design wallpaper",
    "web design vs ux design",
    "web design vs web development",
    "web design w3schools",
    "web design z pattern",
    "web design Yuma AZ",
    "web design youtube tutorial",
    "web design your way",
    "web design youtube channels",
    "web development bd",
    "web development banner",
    "web development bangla book pdf",
    "web development app for PC",
    "web development Angela Yu",
    "web development and web designing difference",
    "web development definition",
    "web development course in Chittagong",
    "web development hashtags",
    "web development HD images",
    "web development job salary",
    "web development jobs",
    "web development job in USA",
    "web development job in Germany",
    "web development job in bd",
    "web development introduction",
    "web development logo",
    "web development logo png",
    "web development market size",
    "web development life cycle",
    "web development learning time",
    "web development learning",
    "web development or graphic design which is better",
    "web development or digital marketing which is better",
    "web development or app development",
    "web development online jobs",
    "web development online course",
    "web development quantum pdf",
    "web development qualifications",
    "web development projects for students",
    "web development programming languages",
    "web development programming hero",
    "web development quotes",
    "web development quotation",
    "web development quora",
    "web development questions and answers pdf",
    "web development questions",
    "web development software free",
    "web development salary",
    "web development roadmap 2023",
    "web development services",
    "web development software",
    "web development services list",
    "web development using react js",
    "web development using PHP notes pdf",
    "about Massachusetts Institute of Technology",
    "it new technology",
    "is technology developing faster than it used to",
    "is technology a blessing",
    "is information technology a course",
    "Jaypee Institute of Information Technology",
    "linear technology",
    "Manipal Institute of Technology",
    "Lamar Institute of Technology",
    "Lake Washington Institute of Technology",
    "Lagos State University of Science and Technology",
    "La Crosse Technology",
    "Missouri University of Science and Technology",
    "Must Energy (Guangdong) Technology",
    "medical technology",
    "Massachusetts Institute of Technology notable alumni",
    "must-have office technology",
    "must-have technology",
    "must-have technology 2022",
    "must-have technology for the classroom",
    "National Institute of Standards and Technology",
    "must-read technology books",
    "new battery technology",
    "new technology",
    "polygon technology",
    "planet technology",
    "Pennsylvania College of Technology",
    "PAR Technology",
    "on the cutting edge of technology"],
  authors: [{ name: "Siam Ahnaf", url: "https://www.siamahnaf.com/" }],
  colorScheme: "only light",
  creator: "Cabbage web",
  publisher: "Cabbage web",
  metadataBase: new URL("https://www.cabbageweb.com"),
  openGraph: {
    title: "Cabbage | The harmony of code and design!",
    description: "We're Pioneering Design-Driven Web Innovators. Where Vision Becomes Reality, Empowering startups, businesses, and ideas to flourish, solving challenges with the art of coding.",
    url: "https://www.cabbageweb.com/",
    siteName: "Cabbage web",
    images: [
      {
        url: "/open-graph.png",
        width: 1640,
        height: 924,
      }
    ],
    type: "website"
  },
  themeColor: "light",
  category: "Web Development"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} font-sans text-main`}>
      <body className={inter.className}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
